source 'https://rubygems.org'
ruby '2.3.4'
#ruby=2.3.4@ccm_platform

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end



gem 'rails', '5.0.2'
gem 'pg', '0.20.0'
gem 'puma', '3.10.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'devise', '4.2.1'
gem 'annotate', '2.7.1'
gem 'foundation-rails', '6.3.1.0 '
gem 'exception_notification', '4.2.1'
gem 'angularjs-rails', '1.6.2'
gem 'kaminari', '1.0.1'
gem 'dragonfly', '1.1.4'
gem 'dragonfly-s3_data_store', '1.3.0'
gem 'rolify', '5.1.0'
gem 'cancancan', '1.16.0'
gem 'mailboxer', '0.14.0'
gem 'gritter', '1.2.0'
gem 'validic', '0.6.1'
gem 'rack-cors', '1.0'
gem 'active_model_serializers', '0.10.6'
gem 'aescrypt', '1.0.0'
gem 'aes', '0.5.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener', '1.4.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
